-- =====================================================
-- Courier Data SQLite Database Schema
-- This file shows the database structure
-- The actual .sqlite file is auto-generated by PHP
-- =====================================================

-- Enable foreign keys
PRAGMA foreign_keys = ON;

-- =====================================================
-- Table: tracking_searches
-- Logs all parcel tracking lookups
-- =====================================================
CREATE TABLE IF NOT EXISTS tracking_searches (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    tracking_number TEXT NOT NULL,
    has_result INTEGER DEFAULT 0,          -- 0 = not found, 1 = found
    result_status TEXT,                     -- e.g., "Delivered", "In Transit"
    search_timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
    ip_address TEXT,                        -- Visitor IP for analytics
    user_agent TEXT                         -- Browser info (max 255 chars)
);

-- Index for faster tracking number lookups
CREATE INDEX IF NOT EXISTS idx_tracking_number 
ON tracking_searches(tracking_number);

-- =====================================================
-- Table: quote_requests
-- Logs all shipping quote requests
-- =====================================================
CREATE TABLE IF NOT EXISTS quote_requests (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    suburb TEXT NOT NULL,                   -- Destination suburb
    postal_code TEXT NOT NULL,              -- 4-digit postal code
    rf_code TEXT DEFAULT 'JNB',             -- Origin franchise code
    weight REAL NOT NULL,                   -- Parcel weight in kg
    services_count INTEGER DEFAULT 0,       -- Number of services returned
    cheapest_price REAL,                    -- Lowest quoted price (ZAR)
    request_timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
    ip_address TEXT,                        -- Visitor IP for analytics
    user_agent TEXT                         -- Browser info (max 255 chars)
);

-- Index for location-based analytics
CREATE INDEX IF NOT EXISTS idx_quote_location 
ON quote_requests(suburb, postal_code);

-- =====================================================
-- Sample Data (for testing)
-- =====================================================

-- Sample tracking searches
INSERT INTO tracking_searches (tracking_number, has_result, result_status, ip_address) VALUES
('A123456789', 1, 'Delivered', '192.168.1.1'),
('B987654321', 1, 'In Transit', '192.168.1.2'),
('C111222333', 0, NULL, '192.168.1.3');

-- Sample quote requests
INSERT INTO quote_requests (suburb, postal_code, rf_code, weight, services_count, cheapest_price, ip_address) VALUES
('Sandton', '2196', 'JNB', 2.5, 3, 89.50, '192.168.1.1'),
('Cape Town', '8001', 'JNB', 5.0, 4, 145.00, '192.168.1.2'),
('Durban', '4001', 'JNB', 1.0, 2, 65.00, '192.168.1.3');
